### ISSUE TITLE
Missing source distribution

### ISSUE THREAD

**Issue by pavelzw** [kolibril13/jupyter-tldraw#15]
For this package to be repackaged to conda-forge, it would be nice if you included source distributions in pypi
![image](https://github.com/kolibril13/jupyter-tldraw/assets/29506042/b09d36ec-1fca-43ec-aa54-2e61992ee484)

**Comment by thewchan** [comment]
I was able to the v2.0.2 up to conda forge, but the most recent version seems to build JS code as well, but the JS code isn't shipped with the sdist and therefore we aren't able to build the most recent tldraw verison on Conda Froge.

**Comment by thewchan** [comment]
https://github.com/conda-forge/tldraw-feedstock/pull/1
